name: Build and Push Python Backend Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Poetry using pip
    - name: Install Poetry
      run: pip install poetry

    # Install project dependencies using Poetry
    - name: Install dependencies
      run: poetry install

    # Black formatter check
    - name: Black formatter
      run: poetry run black --check .
    
    # Run pylint
    - name: Lint with pylint
      run: poetry run pylint ./leisair_ml

    # Log in to a Docker registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/leisair-ml:latest
